<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'prod_name' => 'Bottega Le Essenza Absolute Boy EDP For Men',
                'price' => 1000000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A bold and masculine fragrance with a refined woody aroma',
                'top_notes' => 'Citrus',
                'mid_notes' => 'Spices',
                'base_notes' => 'Cedarwood',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Men',
                'age_group' => 'Adult',
                'keyword' => 'woody',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'YSL Cinema EDP For Women',
                'price' => 1350000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A glamorous and elegant scent with floral and vanilla notes',
                'top_notes' => 'Clementine',
                'mid_notes' => 'Almond Blossom',
                'base_notes' => 'Vanilla',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Women',
                'age_group' => 'Adult',
                'keyword' => 'floral',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Burberry Weekend EDP For Women',
                'price' => 825000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A light and refreshing floral fragrance, perfect for casual wear',
                'top_notes' => 'Mandarin, Sage, Mignonette',
                'mid_notes' => 'Blue Hyacinth, Nectarine, Peach Blossom, Violet Root, Iris, Red Cyclamen, and Rose Hip',
                'base_notes' => 'Sandalwood, Musk, Cedarwood',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Women',
                'age_group' => 'Young and Adult',
                'keyword' => 'floral',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Mont Blanc Starwalker EDT For Men',
                'price' => 900000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A sophisticated and modern scent with a fresh, woody-spicy essence',
                'top_notes' => 'Bergamot',
                'mid_notes' => 'Star Anise',
                'base_notes' => 'Sandalwood',
                'concentration' => 'EDT',
                'fragrance_gender' => 'Men',
                'age_group' => 'Adult',
                'keyword' => 'woody',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Burberry Touch EDP For Women 100ML',
                'price' => 1200000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A delicate and warm floral scent with musky undertones',
                'top_notes' => 'Blackcurrant',
                'mid_notes' => 'Jasmine',
                'base_notes' => 'Vanilla',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Women',
                'age_group' => 'Young Adult',
                'keyword' => 'floral',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Dior Sauvage Parfum For Men 100ML',
                'price' => 2100000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A powerful and intense fragrance with rich, smoky, and spicy notes',
                'top_notes' => 'Bergamot',
                'mid_notes' => 'Sichuan Pepper',
                'base_notes' => 'Vanilla',
                'concentration' => 'Parfum',
                'fragrance_gender' => 'Men',
                'age_group' => 'Adult',
                'keyword' => 'spicy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Bottega Le Essenza Absolute Girl EDP For Women 100ML',
                'price' => 1000000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A charming and feminine perfume with a sweet floral aroma',
                'top_notes' => 'Fruity Notes',
                'mid_notes' => 'Peony',
                'base_notes' => 'Vanilla',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Women',
                'age_group' => 'Young Adult',
                'keyword' => 'floral',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Gucci Bloom EDP For Women 100ML',
                'price' => 1800000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A luxurious and rich floral fragrance with jasmine and tuberose notes',
                'top_notes' => 'Jasmine',
                'mid_notes' => 'Tuberose',
                'base_notes' => 'Sandalwood',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Women',
                'age_group' => 'Adult',
                'keyword' => 'floral',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Calvin Klein Sheer Beauty for Women',
                'price' => 950000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A fresh and radiant floral fragrance with soft, feminine notes',
                'top_notes' => 'Bergamot',
                'mid_notes' => 'Peony',
                'base_notes' => 'Sandalwood',
                'concentration' => 'EDT',
                'fragrance_gender' => 'Women',
                'age_group' => 'Young Adults',
                'keyword' => 'floral',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Mark Alfred Magical Night',
                'price' => 1250000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'An enchanting fragrance with deep oriental and floral notes',
                'top_notes' => 'Blackurrant',
                'mid_notes' => 'Jasmine',
                'base_notes' => 'Oud',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Unisex',
                'age_group' => 'Adults',
                'keyword' => 'oriental',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Dior Homme',
                'price' => 1900000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A refined and modern fragrance with woody and powdery accords',
                'top_notes' => 'Lavender',
                'mid_notes' => 'Iris',
                'base_notes' => 'Leather',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Men',
                'age_group' => 'Adults',
                'keyword' => 'woody',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'YSL Mon Paris',
                'price' => 1600000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A sweet and passionate fragrance with fruity and floral notes',
                'top_notes' => 'Strawberry',
                'mid_notes' => 'Jasmine',
                'base_notes' => 'Patchouli',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Women',
                'age_group' => 'Young Adults',
                'keyword' => 'floral',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Versace Eros EDT For Men',
                'price' => 1300000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'Fresh and woody fragrance with mint, green apple, and tonka bean.',
                'top_notes' => 'Mint, Green Apple, Lemon',
                'mid_notes' => 'Tonka Bean, Geranium, Ambroxan',
                'base_notes' => 'Vanilla, Oakmoss, Cedar, Vetiver',
                'concentration' => 'EDT',
                'fragrance_gender' => 'Men',
                'age_group' => 'Adult',
                'keyword' => 'fresh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Lancome La Vie Est Belle EDP',
                'price' => 1450000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'Floral and sweet scent with iris, praline, and vanilla.',
                'top_notes' => 'Blackcurrant, Pear',
                'mid_notes' => 'Iris, Jasmine, Orange Blossom',
                'base_notes' => 'Praline, Vanilla, Patchouli, Tonka Bean',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Women',
                'age_group' => 'Adult',
                'keyword' => 'sweet',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Paco Rabanne 1 Million EDT For Men',
                'price' => 1550000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'Warm and spicy scent with cinnamon and leather.',
                'top_notes' => 'Blood Mandarin, Grapefruit, Mint',
                'mid_notes' => 'Cinnamon, Rose, Spicy Notes',
                'base_notes' => 'Leather, Amber, Woody Notes',
                'concentration' => 'EDT',
                'fragrance_gender' => 'Men',
                'age_group' => 'Adult',
                'keyword' => 'spicy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Jo Malone Peony & Blush Suede',
                'price' => 1750000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'Soft floral scent with red apple and suede notes.',
                'top_notes' => 'Red Apple',
                'mid_notes' => 'Peony, Jasmine, Rose',
                'base_notes' => 'Suede, Musk',
                'concentration' => 'Cologne',
                'fragrance_gender' => 'Women',
                'age_group' => 'Adult',
                'keyword' => 'floral',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Chanel Chance Eau Tendre',
                'price' => 1600000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'Fruity-floral scent with grapefruit and jasmine.',
                'top_notes' => 'Grapefruit, Quince',
                'mid_notes' => 'Jasmine, Hyacinth',
                'base_notes' => 'Musk, Iris, Cedar',
                'concentration' => 'EDT',
                'fragrance_gender' => 'Women',
                'age_group' => 'Teen',
                'keyword' => 'fresh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Tom Ford Black Orchid EDP',
                'price' => 1900000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'Luxurious and dark fragrance with truffle and patchouli.',
                'top_notes' => 'Truffle, Ylang-Ylang, Blackcurrant',
                'mid_notes' => 'Orchid, Lotus, Spices',
                'base_notes' => 'Patchouli, Incense, Sandalwood',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Unisex',
                'age_group' => 'Adult',
                'keyword' => 'oriental',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Dolce & Gabbana Light Blue',
                'price' => 1350000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'Fresh and citrus scent with Sicilian lemon and cedar.',
                'top_notes' => 'Sicilian Lemon, Apple',
                'mid_notes' => 'Bamboo, Jasmine, White Rose',
                'base_notes' => 'Cedar, Musk, Amber',
                'concentration' => 'EDT',
                'fragrance_gender' => 'Women',
                'age_group' => 'Adult',
                'keyword' => 'fresh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Bvlgari Man in Black',
                'price' => 1650000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'Bold and intense with rum, leather, and spices.',
                'top_notes' => 'Spices, Rum, Tobacco',
                'mid_notes' => 'Leather, Iris, Tuberose',
                'base_notes' => 'Guaiac Wood, Tonka Bean, Benzoin',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Men',
                'age_group' => 'Adult',
                'keyword' => 'masculine',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Maison Francis Kurkdjian Baccarat Rouge 540',
                'price' => 3000000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A luxurious and radiant scent with saffron, amberwood, and fir resin.',
                'top_notes' => 'Saffron, Jasmine',
                'mid_notes' => 'Amberwood, Ambergris',
                'base_notes' => 'Fir Resin, Cedar',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Unisex',
                'age_group' => 'Adult',
                'keyword' => 'amber',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Chanel Bleu de Chanel',
                'price' => 2300000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A woody aromatic fragrance for the man who defies convention.',
                'top_notes' => 'Lemon, Mint, Pink Pepper',
                'mid_notes' => 'Ginger, Nutmeg, Jasmine',
                'base_notes' => 'Sandalwood, Cedar, Amber',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Men',
                'age_group' => 'Adult',
                'keyword' => 'masculine',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Narciso Rodriguez Musc Noir Rose EDP For Women',
                'price' => 1850000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A sensual reinterpretation of a classic musky floral fragrance, enhanced with rose and tuberose.',
                'top_notes' => 'Plum, Pink Pepper, Bergamot',
                'mid_notes' => 'Rose, Tuberose, Musk',
                'base_notes' => 'Vanilla, Suede',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Women',
                'age_group' => 'Adult',
                'keyword' => 'musk',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Dolce & Gabbana L’Imperatrice 3 EDT For Women',
                'price' => 1600000,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A vibrant and energetic fragrance blending exotic fruits with bright pink florals.',
                'top_notes' => 'Rhubarb, Kiwi, Red Currant',
                'mid_notes' => 'Watermelon, Cyclamen, Jasmine',
                'base_notes' => 'Lemon Tree, Musk, Sandalwood',
                'concentration' => 'EDT',
                'fragrance_gender' => 'Women',
                'age_group' => 'Teen, Adult',
                'keyword' => 'fruity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prod_name' => 'Victoria Hills Victoria Couture EDP For Unisex',
                'price' => 1200000.,
                'uploaded_by' => 1,
                'is_listed' =>1,
                'description' => 'A versatile unisex scent combining elegance and modern freshness with a touch of warm wood.',
                'top_notes' => 'Bergamot, Apple, Lavender',
                'mid_notes' => 'Iris, Jasmine, Amber',
                'base_notes' => 'Cedarwood, Tonka Bean, Musk',
                'concentration' => 'EDP',
                'fragrance_gender' => 'Unisex',
                'age_group' => 'Adult',
                'keyword' => 'elegant',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
